### PR TITLE
Replace complex pool with mutex pool

### LINKED ISSUE #65: Pool::get_conn hangs under contention
The following (new) test case occasionally hangs for me:
```rust
#[test]
fn can_handle_the_pressure() {
    let mut runtime = tokio::runtime::Runtime::new().unwrap();
    let pool = Pool::new(&**DATABASE_URL);
    for _ in 0..100 {
        use futures::{Sink, Stream};
        let (tx, rx) = futures::sync::mpsc::unbounded();
        for i in 0..10_000 {
            let pool = pool.clone();
            let tx = tx.clone();
            runtime.spawn(futures::future::lazy(move || {
                pool.get_conn()
                    .map_err(|e| unreachable!("{:?}", e))
                    .and_then(move |_| {
                        tx.send(i).map_err(|e| unreachable!("{:?}", e))
                    }).map(|_| ())
            }));
        }
        drop(tx);
        runtime.block_on(rx.fold(0, |_, _i| {
            Ok(0)
        })).unwrap();
    }
    drop(pool);
    runtime.shutdown_on_idle().wait().unwrap();
}
```
It specifically tries to set up contention over the `Pool` (notice that it doesn't actually issue any queries, it just repeatedly "gets" connections and then return them immediately), and it seems like occasionally it hits a deadlock. This _may_ be related to #64, but I'm not sure.

### PR DESCRIPTION
**Pull request by jonhoo**
Fixes #65

### CODE REVIEW

**Comment by jonhoo** [comment]
Hmm, the test on `8.0` seems unrelated to this change @blackbeam ?

**Comment by jonhoo** [comment]
Anecdotally, this eliminates the connection leaking I was seeing that was causing #65.

**Comment by jonhoo** [comment]
I discovered a race, so hold off on merging this for a little bit.

**Comment by jonhoo** [comment]
Okay, I think that last commit fixed it, and that this is now ready.

**Comment by jonhoo** [comment]
Bah, apparently not -- will dig more.

**Comment by jonhoo** [comment]
Phew, okay, that should do it!

**Comment by jonhoo** [comment]
@blackbeam Can we do a point release with this change?

**Comment by blackbeam** [comment]
@jonhoo, I'll publish master as v0.22.0.
Please tell me if you need a more precise release with only this change.

**Comment by jonhoo** [comment]
No, a major release is fine too :)

**Pull request merged**
