### PR TITLE
Add support for std::future and async/await

### LINKED ISSUE #63: Support for std::future and async/await
`std::future` is now in 1.36.0 and async/await is going to (hopefully) be stabilized in 1.38.0. Opening up this issue to track progress on upgrading mysql_async to the new syntax.

Is anybody working on this already? We might be able to put some hours to the refactoring in Prisma later on.

### PR DESCRIPTION
**Pull request by jonhoo**
Still a work in progress.

This is a _very_ direct port of the existing codebase. I'm avoiding rearchitecting as much as I can, and instead doing a mostly mechanical transformation. Seems to be going okay so far, but I'm not quite done yet (need https://github.com/tokio-rs/tokio/pull/1537 for example). There are definitely a bunch of places the codebase could be improved (in particular, a bunch of `Box`es that could be removed), but at least this will get us off the ground.

Fixes #63.

### CODE REVIEW

**Comment by jonhoo** [comment]
Will also need someone with access to a Windows machine to port https://github.com/nikvolf/tokio-named-pipes. Shouldn't be _too_ hard I think.

**Comment by jonhoo** [comment]
Currently seemingly stuck on https://github.com/rust-lang/rust/issues/46415#issuecomment-528099782 -- the compiler runs out of stack when trying to compile the code, presumably due to a cyclic `async fn` somewhere.

**Comment by jonhoo** [comment]
I think in theory we could also improve some of the APIs a fair amount as part of this process. For example, we no longer really need to have all the futures return `Self`, since we can now take `&mut self` instead!

**Comment by blackbeam** [comment]
It's a lot of work, thanks!

> Will also need someone with access to a Windows machine to port https://github.com/nikvolf/tokio-named-pipes. Shouldn't be too hard I think.

I've downloaded a fresh image from https://developer.microsoft.com/en-us/windows/downloads/virtual-machines a week ago, but I'm not sure on how soon i would be able to work on this. I need to close some education-related stuff during this weekend because of a deadline.

**Comment by jonhoo** [comment]
@blackbeam I actually reached out to @nikvolf (the maintainer) and got a reply saying they'd take a look!

**Comment by PvdBerg1998** [comment]
Thanks for your work! Looking forward to finally ditching futures 0.1 (this is my last dependency using it)!

**Comment by jonhoo** [comment]
Tests now pass on CircleCI (though they require nightly of course). Windows won't work until we have `tokio-named-pipes`, so I think that's the blocker for now?

Also, @blackbeam, how would you feel about moving to Azure Pipelines using https://github.com/crate-ci/azure-pipelines ? It's pretty easy to set up, and would mean we don't have to have two configs that have tons of random command strings everywhere.

**Comment by PvdBerg1998** [comment]
@jonhoo I've looked into porting `tokio-named-pipes` but it seems the crate is redundant now, you can just use `PollEvented` directly I think. See https://github.com/tokio-rs/tokio/blob/f1f61a3b15d17767b12bfd8c0c5712db1b089b0b/tokio-net/src/util/poll_evented.rs#L356.

**Comment by jonhoo** [comment]
@PvdBerg1998 Ah interesting.. Trying that now.

**Comment by jonhoo** [comment]
:tada: I think we are now only blocked on a release for https://github.com/tokio-rs/tokio/pull/1537 before we could push out an alpha of this @blackbeam!

**Comment by PvdBerg1998** [comment]
I'll try it in my codebase. Just fyi, it doesn't compile for me because you're using `pin-project` alpha 10 instead of 7, which creates issues with tokio/hyper.

**Comment by jonhoo** [comment]
Oh, that's awkward. What is it that fails? Presumably cargo should just compile both versions?

**Comment by PvdBerg1998** [comment]
Yeah I've been trying to patch it but it's being difficult for some reason. The error is:
```
versions that meet the requirements ^0.4.0-alpha.10 are: 0.4.0-alpha.10

all possible versions conflict with previously selected packages.

  previously selected package pin-project v0.4.0-alpha.7
    ... which is depended on by hyper v0.13.0-alpha.1`
    ... which is depended on by hyper-tls v0.4.0-alpha.1`
    ... which is depended on by projectname

failed to select a version for `pin-project` which could resolve this conflict
```
I tried patching it using `pin-project = { version = "^0.4.0-alpha.10" }` but `patch for pin-project in https://github.com/rust-lang/crates.io-index points to the same source, but patches must point to different sources` :(

**Comment by jonhoo** [comment]
@taiki-e Can you shed some light on the issue above?

**Comment by PvdBerg1998** [comment]
Ok so I just got cargo to panic 😅

**Comment by taiki-e** [comment]
> Can you shed some light on the issue above?

This is because pin-project is still alpha, so hyper is pinning that version. I think it needs to update version of pin-project in hyper and add the following block to Cargo.toml:
```toml
[patch.crates-io]
hyper = { git = "https://github.com/hyperium/hyper", version = "0.13.0-alpha.1" }
```

**Comment by PvdBerg1998** [comment]
@jonhoo I forked `hyper` and patched their dependency. It still doesn't compile because tokio master changed something. But: I'm getting a compilation error in `async_tls`:
```
error[E0277]: the trait bound `S: tokio_io::async_read::AsyncRead` is not satisfied
   --> C:\Users\pim\.cargo\git\checkouts\mysql_async-a98a8705a879e6ef\c859e17\src\io\async_tls.rs:112:26
    |
112 |         inner: connector.connect(domain, stream).await?,
    |                          ^^^^^^^ the trait `tokio_io::async_read::AsyncRead` is not implemented for `S`
    |
    = help: consider adding a `where S: tokio_io::async_read::AsyncRead` bound

error[E0277]: the trait bound `S: tokio_io::async_write::AsyncWrite` is not satisfied
   --> C:\Users\pim\.cargo\git\checkouts\mysql_async-a98a8705a879e6ef\c859e17\src\io\async_tls.rs:112:26
    |
112 |         inner: connector.connect(domain, stream).await?,
    |                          ^^^^^^^ the trait `tokio_io::async_write::AsyncWrite` is not implemented for `S`
    |
    = help: consider adding a `where S: tokio_io::async_write::AsyncWrite` bound
```

**Comment by PvdBerg1998** [comment]
I forked the PR and removed the `#[cfg()]` so I can test it on Windows. Calling `Pool::disconnect` never returns for me.

**Comment by PvdBerg1998** [comment]
Other functionality seems to work :tada:

**Comment by jonhoo** [comment]
@blackbeam what do you think still remains for this?

**Comment by blackbeam** [comment]
@jonhoo, patch section should be removed from Cargo.toml. But at the moment this won't work, because tokio-rs/tokio#1537 not yet published.

**Comment by pimeys** [comment]
How hard it would be to make all the methods taking self by value to make them to be by reference? Right now abstracting mysql to a more generic database crate is not that easy due to other crates just using references. At least tokio-postgres uses an approach where you have a `Client` and `Connection` which communicating through a channel. In addition to a cleaner interface, this approach also allows us to do stuff like rolling back a transaction in `Drop` if not commited yet.

**Comment by jonhoo** [comment]
@pimeys so, I took a quick look at that when I did this PR, and while in theory it shouldn't be too bad, in practice a tonne of the code relies on being able to move in and out of things. This is (as you probably guessed) because much of the state keeping for each connection is done inside the `Connection` instance itself, rather than in some spawned state machine that is accessed through a channel. This has upsides (you don't have to own arguments to `execute`) and downsides (`Connection` can't easily be cloned and all receivers take `self`). I think changing this would be a larger refactoring.

**Comment by blackbeam** [comment]
@pimeys, that's interesting. Looks like major change to the current architecture. I'm not sure, however, about pros of this approach except API convenience.

**Comment by jonhoo** [comment]
@blackbeam It does make the API _much_ nicer to use, because you no longer need to "chain along" `Self` by doing things like:
```rust
let result = c.query("...").await?;
let (c, rows) = result.collect_and_drop().await?;
let c = c.drop_query("...").await?;
```
instead you can just write code without moving `c`:
```rust
let rows = c.query("...").await?.collect_and_drop().await?;
c.drop_query("...").await?;
```

**Comment by blackbeam** [comment]
@jonhoo, agree with that. I believe it worth, at least, to try to implement it to measure the consequences.

**Comment by pimeys** [comment]
We here at Prisma are abstracting the databases (psql, mysql, sqlite) under our [own connector crate](https://github.com/prisma/prisma-query/), and right now with the sync crates the generic connector is very easy to do. Not that much when we switch to async execution, due to mysql being completely different than the others.

I've been reading the tokio postgres code a lot and they seem to have a nice way of making it to work:

https://github.com/sfackler/rust-postgres/blob/std-futures/tokio-postgres/src/client.rs#L176

What makes their way even sweeter the way the transactions can be rolled back in `Drop`:

https://github.com/sfackler/rust-postgres/blob/std-futures/tokio-postgres/src/transaction.rs#L27

Now your transaction can work like the sync counterpart. If you error out, RAII takes care of the rollback.

**Comment by blackbeam** [comment]
@pimeys, btw, `mysql_async` transaction must rollback if not committed (at least if tokio runtime is aliver). Please file an issue if you experienced the opposite.

**Comment by blackbeam** [comment]
Published as [v0.21.0-alpha.1](https://github.com/blackbeam/mysql_async/releases/tag/v0.21.0-alpha.1)

**Comment by blackbeam** [comment]
@jonhoo, @pimeys,

New non-consuming API is available in [v0.24.0-alpha](https://crates.io/crates/mysql_async/0.24.0-alpha). Could you, please, test it? ([api docs](https://docs.rs/mysql_async/0.24.0-alpha/mysql_async/index.html))

**Comment by tomhoule** [comment]
I haven't tried very hard, but trying to use 0.24.0 alpha in quaint (https://github.com/prisma/quaint/pull/117), we get a compile error from one of the dependecies:

```
    Checking time v0.2.8
error: expected an item keyword
   --> /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.2.8/src/utc_offset.rs:366:13
    |
366 |             let tm = timestamp_to_tm(datetime.timestamp())?;
    |             ^^^

error: aborting due to previous error
```

(it's one of mysql_common's dependencies).

**Comment by blackbeam** [comment]
@tomhoule, this looks like [this issue](). I believe `cargo update` should help.

[this issue]: https://github.com/time-rs/time/pull/234

**Pull request merged**
