### PR TITLE
Update tokio to 1.0 (fix #132)

### LINKED ISSUE #132: Panic while getting connection from pool (support for tokio-0.3?)
With the tokio-0.3.3, I am seeing panic error while getting connection from the pool. This was working fine with tokio-2.x version.

tokio version:0.3.3
mysql_asybc: 0.25.0

tokio runtime created using: Builder::new_multi_thread()

```
  0:        0x10f5a9394 - std::backtrace_rs::backtrace::libunwind::trace::hb4ff9014ec5817b3
                               at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/std/src/../../backtrace/src/backtrace/libunwind.rs:100:5
   1:        0x10f5a9394 - std::backtrace_rs::backtrace::trace_unsynchronized::h0d03cf0f7c5d8d01
                               at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10f5a9394 - std::sys_common::backtrace::_print_fmt::h5b2bf2921eea85ae
                               at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x10f5a9394 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h808cc0fc691f5922
                               at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x10f5ceb30 - core::fmt::write::h0ce880d33cd2a300
                               at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/core/src/fmt/mod.rs:1076:17
   5:        0x10f5a1b46 - std::io::Write::write_fmt::h057e6b5365b25cdb
                               at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/std/src/io/mod.rs:1516:15
   6:        0x10f5ab4d9 - std::sys_common::backtrace::_print::ha1932a5f36d2b146
                               at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x10f5ab4d9 - std::sys_common::backtrace::print::had07999cb13bdf77
                               at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x10f5ab4d9 - std::panicking::default_hook::{{closure}}::hcbe1ecfff77305a1
                               at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/std/src/panicking.rs:208:50
   9:        0x10f5ab19d - std::panicking::default_hook::h8422621c02c35b35
                               at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/std/src/panicking.rs:227:9
  10:        0x10f5abaab - std::panicking::rust_panic_with_hook::h82b76d3adf4cbc3a
                               at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/std/src/panicking.rs:577:17
  11:        0x10f5ab62b - std::panicking::begin_panic_handler::{{closure}}::h1e3858c0f26acd6d
                               at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/std/src/panicking.rs:484:9
  12:        0x10f5a9838 - std::sys_common::backtrace::__rust_end_short_backtrace::hb43bfc309d1c5e68
                               at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/std/src/sys_common/backtrace.rs:141:18
  13:        0x10f5ab5ea - rust_begin_unwind
                               at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/std/src/panicking.rs:483:5
  14:        0x10f5f4f2f - core::panicking::panic_fmt::h33aee6f32da9c3a4
                               at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/core/src/panicking.rs:85:14
  15:        0x10f5f4dba - core::option::expect_failed::he41d9b6b925c99b1
                               at /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/core/src/option.rs:1260:5
  16:        0x10eeb0dde - core::option::Option<T>::expect::ha8ead4dbfc53f3b9
                               at /Users/xxx/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:349:21
  17:        0x10ee93b45 - tokio::task::spawn::spawn::h35bd0066fc875c3c
                               at /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/task/spawn.rs:130:28
  18:        0x10ee44c64 - mysql_async::conn::pool::Exchange::spawn_futures_if_needed::h7b820e5753962bfb
                               at /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/mysql_async-0.25.0/src/conn/pool/mod.rs:79:13
  19:        0x10ee458e6 - mysql_async::conn::pool::Pool::poll_new_conn_inner::h80344d2cc2281d13
                               at /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/mysql_async-0.25.0/src/conn/pool/mod.rs:236:9
  20:        0x10ee4568c - mysql_async::conn::pool::Pool::poll_new_conn::h3266b761607811a0
                               at /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/mysql_async-0.25.0/src/conn/pool/mod.rs:223:9
  21:        0x10ee7efa2 - <mysql_async::conn::pool::futures::get_conn::GetConn as core::future::future::Future>::poll::hab19b271f37ed892
                               at /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/mysql_async-0.25.0/src/conn/pool/futures/get_conn.rs:77:51
```

### PR DESCRIPTION
**Pull request by blackbeam**

### CODE REVIEW

**Comment by udoprog** [comment]
So `NamedPipe` support in Tokio appears to be the last blocker (ref https://github.com/tokio-rs/tokio/issues/3118).

The `PollEvented` type is now private, and support for named pipes [has been merged into mio](https://github.com/tokio-rs/mio/pull/1351) already. I have a compiling prototype and would be willing to work on getting it into Tokio unless you're already doing so?

**Comment by udoprog** [comment]
Here's my branches if someone wants to give it a shot:
Tokio: https://github.com/udoprog/tokio/tree/named-pipes
mysql_async: https://github.com/udoprog/mysql_async/tree/tokio1

I'll try it later when I can get a working mariadb installation up and running, but can't right now!

**Comment by blackbeam** [comment]
Hi, @udoprog.

Looks like we've started this at the same time (see tokio-rs/tokio#3388), however I not yet have a working `mysql_async` version based on my fork.

Regarding `mysql_async` update: I think it's reasonable to remove NamedPipes support for now and reintroduce later when it'll be merged into `tokio`.

**Comment by udoprog** [comment]
> Hi, @udoprog.
> 
> Looks like we've started this at the same time (see [tokio-rs/tokio#3388](https://github.com/tokio-rs/tokio/pull/3388)), however I not yet have a working `mysql_async` version based on my fork.
> 
> Regarding `mysql_async` update: I think it's reasonable to remove NamedPipes support for now and reintroduce later when it'll be merged into `tokio`.

That is fine by me! I'm just motivated to get a new release of your wonderful library out the door ASAP.

I'd be glad to help in any way I can!

**Pull request merged**
