### PR TITLE
fix should_run_transactions when db is not 't'

### PR DESCRIPTION
**Pull request by brunoqc**
The test failed when my DATABASE_URL's database was 'test'.

### CODE REVIEW

**Comment by blackbeam** [comment]
This is strange. Database in DATABASE_URL should not break tests in any case. Also with this pr test will fail if no database in DATABASE_URL. Maybe this problem is related to mariadb?
What is the actual error message you see when DATABASE_URL's database is 'test'?

**Comment by brunoqc** [comment]
> ---- conn::test::should_run_transactions stdout ----
	thread 'conn::test::should_run_transactions' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Server(ERROR 1044 (42000): Access denied for user 'testsql'@'%' to database 't'), (None, None))', ../src/libcore/result.rs:837

Is `t` a system database?

**Comment by blackbeam** [comment]
> Is t a system database?

No. `t` is not exist because
> You can create a TEMPORARY table in a nonexistent database if you qualify the table name with the database name in the CREATE TABLE statement. In this case, all subsequent references to the table must be qualified with the database name.

I think the actual problem here is the rights of a user connected to database.

We could look into opts to discover database or fallback to `t`, but it won't work if DATABASE_URL will specify connection as unprivileged user with no database.

The only solution i see is to state that test requires root privileges.

Am i missing something?

**Comment by brunoqc** [comment]
> The only solution i see is to state that test requires root privileges.

I think root privileges is too much since I was able to run all the tests with:
```sql
CREATE USER 'testsql'@'%' IDENTIFIED BY 'testsql';
GRANT ALL PRIVILEGES ON test.* TO 'testsql'@'%' WITH GRANT OPTION;
```

With root privileges I wouldn't want to run those tests on my production server but I would with a user that has 'ALL PRIVILEGES' on a test database.

In my opinion, the simpler way would be to reject DATABASE_URL if no database is specified.

**Comment by blackbeam** [comment]
> In my opinion, the simpler way would be to reject DATABASE_URL if no database is specified.

Yeah, this should match. Could you please alter pr to panic if no database in DATABASE_URL and to use `mysql` as a default database?

> With root privileges I wouldn't want to run those tests on my production server

Btw. I will add Makefile similar to one used in mysql crate, so `make test` will run separate mysql instance to run tests on it.

**Comment by brunoqc** [comment]
> Could you please alter pr to panic if no database in DATABASE_URL and to use mysql as a default database?

Yes.

> I will add Makefile similar to one used in mysql crate, so make test will run separate mysql instance to run tests on it.

Will it still be possible to use DATABASE_URL with `cargo test` without having to start a separate mysql instance? It would be nice on Windows where I don't want to install MySQL.

**Comment by brunoqc** [comment]
I updated the commit.

**Pull request merged**
