### PR TITLE
Implemented rustls support, fixes #195

### LINKED ISSUE #195: Request: feature to make use of rustls instead of native-tls
Hi! First of all a giant amount of gratitude for all of you for providing this crate.
It worked out of the box and was very pleasant to use.

With that being said. This is currently my only dependency through which
I require native-tls support, all other dependencies that I use do already allow `rustls` support.
Is it on the roadmap already to provide `rustls` support, be it an opt-in feature. It would allow
me to simplify my production processes.

If there is something I can help in this regards to assist in making this happen you can let me know as well.
And once again, thanks for developing and maintaining this crate, it's fantastic :)

### PR DESCRIPTION
**Pull request by TobiasDeBruijn**
This PR adds support for rustls, and makes using a TLS implementation optional.

I've inspired this commit purely on https://github.com/blackbeam/rust-mysql-simple/pull/295 and the documentation for the various crates. I'm not familiar with the workings of rustls or native-tls though.

This PR adds the following features:
 - `flate2-zlib` A `flate` backend is needed to compile this crate. Users of `rustls` will turn off the default features when using it,
 hence causing compilation issues. The usual fix for this is for the user to include flate2 in their own Cargo.toml, though this seems suboptimal. So I've made the default flate2 backend it's own feature for ease of use.
- `native-tls-tls` Yes, the double `tls` is intentional. This enabls the native-tls backend and the required crates for it.
- `rustls-tls` Enables the rustls-tls backend

Hopefully this all is to spec.
Thanks!

### CODE REVIEW

**Comment by TobiasDeBruijn** [comment]
The mysql v57 and v80 tests seem to be failing due to missing `cc` (so unrelated to this PR)

However I'm not sure why `TestBasixLinux *` is failing. I don't think any of the default behavior was changed (i.e. native-tls), so that should work if it was not already failing.

**Comment by rosscanning** [comment]
@TobiasDeBruijn Thanks very much for this, I really wanted mysql without openssl. I don't know about the tests, but your branch is working fine for me (on Linux).

**Comment by TobiasDeBruijn** [comment]
Awesome! Might just be CI then.

**Comment by alakhpc** [comment]
Is there anything still blocking this pr?

**Pull request merged**
