### PR TITLE
Reimplement Pool to be fully asynchronous

### PR DESCRIPTION
**Pull request by jonhoo**
This replaces the guts of the old Pool implementation with one that takes no locks, and thus should never block the reactor (#64). Instead, a "recycler" future is spawned that receives any discarded connections, do whatever cleanup is necessary on them, and then send them back to the clients over a lock-free mpsc-like channel. There's also a fast-path for returning pristine connections that are dropped to the pool directly.

### CODE REVIEW

**Comment by jonhoo** [comment]
@blackbeam I think this is now mostly ready, though it looks like CI is _really_ slow. I noticed you were playing around with Circle CI in #47, but the PR still seems to only be checked by AppVeyor. Any progress on that? AppVeyor is notoriously slow.

**Comment by jonhoo** [comment]
Also note that the test `should_handle_multi_result_sets_where_some_results_have_no_output` hangs on MariaDB, which is what I have installed locally. I also had to make this change https://github.com/blackbeam/mysql_async/pull/66/commits/3730a13c6987e3f0b4a297f6b0e64a608e828582 to match MariaDB's default values for [`max_long_data_size`](https://mariadb.com/kb/en/library/server-system-variables/#max_long_data_size).

**Comment by blackbeam** [comment]
> I noticed you were playing around with Circle CI in #47, but the PR still seems to only be checked by AppVeyor.

Yeah. CircleCI was misconfigured, unfortunately. I've fixed that, but than failed to find a way to trigger build for existing PR (found this [discussion](https://ideas.circleci.com/ideas/CCI-I-316)).

> Also note that the test `should_handle_multi_result_sets_where_some_results_have_no_output` hangs on MariaDB, which is what I have installed locally.

That's strange because 10 days ago CircleCI has succeeded for MariaDB 5.5, 10.3 and 10.4. Which MariaDB version do you use?

> I also had to make this change 3730a13 to match MariaDB's default values for max_long_data_size.

18MB of `A`s is just a strange way to catch regressions in packet handler (mysql packets are split into chunks if packet size is greater than 16MB). That's why `--max_allowed_packet=32M` is added  for CI. Could you please revert this change and reconfigure your environment instead?

**Comment by jonhoo** [comment]
> That's strange because 10 days ago CircleCI has succeeded for MariaDB 5.5, 10.3 and 10.4. Which MariaDB version do you use?

```
mariadb  Ver 15.1 Distrib 10.4.6-MariaDB, for Linux (x86_64) using readline 5.1
```

Looks like Circle CI triggered correctly now, so we'll see what it says!

> Could you please revert this change and reconfigure your environment instead?

Done!

**Comment by jonhoo** [comment]
The one failure there appears to be spurious?

**Comment by blackbeam** [comment]
> The one failure there appears to be spurious?

Yeah. CI is happy after rebuild.
I'll look into it again and than merge.

Btw, could you, if possible, build a flamegraph for your version of the pool?

**Comment by jonhoo** [comment]
One thing to note about this is that `tokio::Runtime::shutdown_on_idle` will now _block_ until all handles to the `Pool` have been dropped, or until `Pool::disconnect` is explicitly called. This is details [here](https://github.com/blackbeam/mysql_async/pull/66/files#diff-d1344942d8599ae90513fe889bbcf58bR712), but should probably be included in the documentation somewhere. It's not clear to me that there's a way to work around this.

**Comment by jonhoo** [comment]
Normal flamegraph for the same benchmark as those in #64 used: https://jon.thesquareplanet.com/share/noria-client-new.svg
Reversed flamegraph shows no more mutex: https://jon.thesquareplanet.com/share/noria-client-new-inv.svg

**Comment by jonhoo** [comment]
@blackbeam I _think_ this will require a major version bump.

**Pull request merged**
