### PR TITLE
v0.28.0 release

### PR DESCRIPTION
**Pull request by blackbeam**

### CODE REVIEW

**Comment by benesch** [comment]
One other thing that would be absolutely swell, @blackbeam, since you were kind enough to merge , would be to make those features optional here too. Unfortunately the only way I know how to do this is to duplicate the features here:

```diff
diff --git a/Cargo.toml b/Cargo.toml
index a4345a7..de54360 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -13,13 +13,14 @@ edition = "2018"
 
 [dependencies]
 bytes = "1.0"
+flate2 = { version = "1.0", default-features = false }
 futures-core = "0.3"
 futures-util = "0.3"
 futures-sink = "0.3"
 lazy_static = "1"
 lru = "0.6.0"
 mio = "0.7.7"
-mysql_common = "0.26.0"
+mysql_common = { version = "0.27.0", default-features = false }
 native-tls = "0.2"
 pem = "0.8.1"
 percent-encoding = "2.1.0"
@@ -42,6 +43,15 @@ rand = "0.8.0"
 
 [features]
 nightly = []
+default = [
+    "flate2/zlib",
+    "mysql_common/bigdecimal",
+    "mysql_common/chrono",
+    "mysql_common/rust_decimal",
+    "mysql_common/time",
+    "mysql_common/uuid",
+    "mysql_common/frunk",
+]
 
 [lib]
 name = "mysql_async"
```

If you're open to this I'd be delighted to submit a PR, though I certainly wouldn't complain if you just integrated the changes here! :D

**Comment by rohitjoshi** [comment]
Looking forward to this release as I need to subscribe for update events (binlog support).

**Comment by blackbeam** [comment]
@rohitjoshi, hi. I still need to fix some hard-to-reproduce issues, but the API shouldn't change.
BTW, have you tried this branch already or you are waiting for the release?

**Comment by rohitjoshi** [comment]
No, I have not tried.  We will prioritize in the next sprint and may use branch for testing.

**Pull request merged**
